sqlite_app/config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  draw :madmin
	authenticate :patron, lambda { |u| u.admin? } do
  	mount Sidekiq::Web => '/sidekiq'
	end

  devise_for :patrons, controllers: { omniauth_callbacks: "patrons/omniauth_callbacks" }
	get '/privacy', to: 'home#privacy'
	get '/terms', to: 'home#terms'
	root to: 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

sqlite_app/app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

sqlite_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

sqlite_app/app/models/notification.rb
class Notification < ApplicationRecord
  include Noticed::Model
  belongs_to :recipient, polymorphic: true
end

sqlite_app/app/models/patron.rb
class Patron < ApplicationRecord
	has_person_name
	has_many :services, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :omniauthable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
	def admin?; true; end
end

sqlite_app/app/models/service.rb
class Service < ApplicationRecord
  belongs_to :patron

  Devise.omniauth_configs.keys.each do |provider|
    scope provider, ->{ where(provider: provider) }
  end

  def client
    send("#{provider}_client")
  end

  def expired?
    expires_at? && expires_at <= Time.zone.now
  end

  def access_token
    send("#{provider}_refresh_token!", super) if expired?
    super
  end


  def twitter_client
    Twitter::REST::Client.new do |config|
      config.consumer_key        = Rails.application.secrets.twitter_app_id
      config.consumer_secret     = Rails.application.secrets.twitter_app_secret
      config.access_token        = access_token
      config.access_token_secret = access_token_secret
    end
  end

  def twitter_refresh_token!(token); end
end

sqlite_app/app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
impersonates :patron,
             method: :current_patron,
             with: ->(id) { Patron.find_by(id: id) }
        include Pundit::Authorization

        def pundit_user
          current_patron
        end
  self.responder = ApplicationResponder
  respond_to :html

end

sqlite_app/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def terms
  end

  def privacy
  end
end

sqlite_app/app/controllers/madmin/application_controller.rb
module Madmin
  class ApplicationController < Madmin::BaseController
    before_action :authenticate_admin_patron

    def authenticate_admin_patron
      # TODO: Add your authentication logic here

      # For example, we could redirect if the user isn't an admin
      # redirect_to "/", alert: "Not authorized." unless user_signed_in? && current_user.admin?
    end

    # Authenticate with Clearance
    # include Clearance::Controller
    # before_action :require_login

    # Authenticate with Devise
    # before_action :authenticate_user!

    # Authenticate with Basic Auth
    # http_basic_authenticate_with(name: Rails.application.credentials.admin_username, password: Rails.application.credentials.admin_password)
  end
end

sqlite_app/app/controllers/madmin/impersonates_controller.rb
class Madmin::ImpersonatesController < Madmin::ApplicationController
  impersonates :patron
  def impersonate
    patron = Patron.find(params[:id])
    impersonate_patron(patron)
    redirect_to main_app.root_path
  end

  def stop_impersonating
    stop_impersonating_patron
    redirect_to main_app.root_path
  end
end

sqlite_app/app/controllers/madmin/patrons_controller.rb
module Madmin
  class PatronsController < Madmin::ResourceController
  end
end

sqlite_app/app/controllers/patrons/omniauth_callbacks_controller.rb
class Patrons::OmniauthCallbacksController <  Devise::OmniauthCallbacksController
  before_action :set_service, except: [:failure]
  before_action :set_patron, except: [:failure]

  attr_reader :service, :patron

  def failure
    redirect_to root_path, alert: "Something went wrong"
  end

  def twitter
		handle_auth "Twitter"
	end

	def linkedin
		handle_auth "Linkedin"
	end

	def google_oauth2
		handle_auth "GoogleOauth2"
	end

	def github
		handle_auth "Github"
	end

	def facebook
		handle_auth "Facebook"
	end

	private

  def handle_auth(kind)
    if service.present?
      service.update(service_attrs)
    else
      patron.services.create(service_attrs)
    end

    if patron_signed_in?
      flash[:notice] = "Your #{kind} account was connected."
      redirect_to edit_patron_registration_path
    else
      sign_in_and_redirect patron, event: :authentication
      set_flash_message :notice, :success, kind: kind
    end
  end

  def auth
    request.env['omniauth.auth']
  end

  def set_service
    @service = Service.where(provider: auth.provider, uid: auth.uid).first
  end

  def set_patron
    if patron_signed_in?
      @patron = current_patron
    elsif service.present?
      @patron = service.patron
    elsif Patron.where(email: auth.info.email).any?
      # 5.Patron is logged out and they login to a new account which doesn't match their old one
      flash[:alert] = "An account with this email already exists. Please sign in with that account before connecting your #{auth.provider.titleize} account."
      redirect_to new_patron_session_path
    else
      @patron = create_patron
    end
  end

  def service_attrs
    expires_at = auth.credentials.expires_at.present? ? Time.at(auth.credentials.expires_at) : nil
    {
      provider: auth.provider,
      uid: auth.uid,
      expires_at: expires_at,
      access_token: auth.credentials.token,
      access_token_secret: auth.credentials.secret,
    }
  end

  def create_patron
    Patron.create(
      email: auth.info.email,
      #name: auth.info.name,
      password: Devise.friendly_token[0,20]
    )
  end

end

sqlite_app/app/helpers/application_helper.rb
module ApplicationHelper
end

sqlite_app/app/helpers/avatar_helper.rb
module AvatarHelper
  def avatar_path(object, options = {})
    size = options[:size] || 180
    default_image = options[:default] || "mp"
    base_url =  "https://secure.gravatar.com/avatar"
    base_url_params = "?s=#{size}&d=#{default_image}"

    if object.respond_to?(:avatar) && object.avatar.attached? && object.avatar.variable?
      object.avatar.variant(resize_to_fill: [size, size])
    elsif object.respond_to?(:email) && object.email
      gravatar_id = Digest::MD5::hexdigest(object.email.downcase)
      "#{base_url}/#{gravatar_id}#{base_url_params}"
    else
      "#{base_url}/00000000000000000000000000000000#{base_url_params}"
    end
  end
end

sqlite_app/app/helpers/bootstrap_helper.rb
module BootstrapHelper
  def bootstrap_class_for(flash_type)
    {
      success: "alert-success",
      error: "alert-danger",
      alert: "alert-warning",
      notice: "alert-primary"
    }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end
end

sqlite_app/app/helpers/home_helper.rb
module HomeHelper
end

sqlite_app/app/views/home/index.html.erb
<h1>Welcome to Silverspoon!</h1>
<p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
<p class="lead">This is just a start to your next big thing.</p>

sqlite_app/app/views/home/privacy.html.erb
<h1>Privacy Policy</h1>
<p class="lead">Use this page as your Privacy Policy</p>

sqlite_app/app/views/home/terms.html.erb
<h1>Terms of Service</h1>
<p class="lead">Use this page as your Terms of Service</p>

sqlite_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-100">
  <head>
    <%= render 'shared/head' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="d-flex flex-column h-100">
    <main class="flex-shrink-0"> 
      <%= render 'shared/navbar' %>
      <%= render 'shared/notices' %>

      <div class="container mt-4 mx-auto">
        <%= yield %>
      </div>
    </main>

    <%= render 'shared/footer' %>
  </body>
</html>

sqlite_app/app/views/madmin/patrons/index.html.erb
<div class="md:flex justify-between items-center space-y-4 md:space-y-0">
  <h1 class="text-xl font-semibold"><%= resource.friendly_name.pluralize %></h1>

  <div class="flex-grow flex md:justify-end gap-4">
    <form class="flex items-center gap-2 relative">
      <%= hidden_field_tag :page, params[:page], value: 1, class: "hidden" %>
      <%= search_field_tag :q, params[:q], placeholder: "Search", class: "rounded-full px-4 focus:bg-white focus:border-indigo-500" %>
      <%= link_to clear_search_params, class: "absolute top-1/2 right-3 text-gray-500 bg-white transform -translate-y-1/2" do %>
        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
          <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clip-rule="evenodd" />
        </svg>
      <% end %>
    </form>

    <%= link_to resource.new_path, class: "bg-white hover:bg-gray-100 text-gray-800 font-semibold py-2 px-4 border border-gray-400 rounded shadow" do %>
      New <span class="hidden md:inline"><%= resource.friendly_name %></span>
    <% end %>
  </div>
</div>

<div class="mb-4">
  <% if resource.scopes.any? %>
    <%= link_to "All", resource.index_path, class: class_names("p-2 rounded", {"bg-gray-100" =>  params[:scope].blank?}) %>
  <% end %>

  <% resource.scopes.each do |scope| %>
    <%= link_to scope.to_s.humanize, resource.index_path(scope: scope), class: class_names("p-2 rounded", {"bg-gray-100" => params[:scope] == scope.to_s}) %>
  <% end %>
</div>
<div class="min-w-full max-w-xl overflow-x-auto pb-4">
  <table class="min-w-full divide-y divide-gray-200">
    <thead>
      <tr class="border-b border-gray-200">
        <% resource.attributes.values.each do |attribute| %>
          <% next if attribute.field.nil? %>
          <% next unless attribute.field.visible?(action_name) %>

          <th class="py-2 px-4 text-left text-xs text-gray-500 font-medium uppercase whitespace-nowrap"><%= sortable attribute.name, attribute.name.to_s.titleize %></th>
        <% end %>
        <th class="py-2 px-4 text-left text-xs text-gray-500 font-medium uppercase">Actions</th>
      </tr>
    </thead>

    <tbody class="text-sm divide-y">
      <% @records.each do |record| %>
        <tr>
          <% resource.attributes.values.each do |attribute| %>
            <% next if attribute.field.nil? %>
            <% next unless attribute.field.visible?(action_name) %>
            <td class="px-4 py-2"><%= render partial: attribute.field.to_partial_path("index"), locals: { field: attribute.field, record: record, resource: resource } %></td>
          <% end %>

          <td class="px-4 py-2 text-center">
            <%= link_to "View", resource.show_path(record), class: "text-indigo-500" %>
            <%= link_to "Edit", resource.edit_path(record), class: "text-indigo-500" %>
            <%= button_to "impersonate", main_app.impersonate_patron_madmin_impersonate_path(record), method: :post %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%== render(partial: 'madmin/pagy/nav', locals: { pagy: @pagy }) if @pagy.pages > 1 %>

sqlite_app/app/views/shared/_footer.html.erb
<footer class="bg-light footer mt-auto py-3">
  <div class="container d-flex justify-content-between mx-auto text-muted">
    <span>&copy; <%= Date.today.year %> Your Company</span>
    <ul class="d-inline float-end list-inline mb-0">
      <li class="list-inline-item mr-3"><%= link_to "Terms", terms_path %></li>
      <li class="list-inline-item mr-3"><%= link_to "Privacy", privacy_path %></li>
    </ul>
  </div>
</footer>

sqlite_app/app/views/shared/_head.html.erb
<title><%= Rails.configuration.application_name %></title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" integrity="sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

sqlite_app/app/views/shared/_navbar.html.erb
<% if current_patron != true_patron %>
  <div class="alert alert-warning text-center">
    You're logged in as <b><%= current_patron.try(:full_name) %> (<%= current_patron.email %>)</b>
    <%= button_to stop_impersonating_patron_madmin_impersonates_path, method: :post do %> Logout <% end %>
  </div>
<% end %>


<nav class="navbar navbar-expand-md navbar-light bg-light">
  <div class="container mx-auto">
    <%= link_to Rails.configuration.application_name, root_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarMain" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarMain">
      <ul class="navbar-nav me-auto mt-2 mt-md-0">
      </ul>

      <ul class="navbar-nav">
        <!--        <li class="nav-item">-->
        
        <!--        </li>-->
        <% if patron_signed_in? %>

        <!--          <li class="nav-item">-->
        
        <!--              <span><i class="far fa-bell" aria-hidden="true"></i></span>-->
        
        <!--          </li>-->

        <li class="nav-item dropdown">
          <%= link_to "#", id: "navbar-dropdown", class: "nav-link dropdown-toggle", data: { target: "nav-account-dropdown", bs_toggle: "dropdown" }, aria: { haspopup: true, expanded: false } do %>
            <%= image_tag avatar_path(current_patron, size: 40), height: 20, width: 20, class: "rounded" %>
          <% end %>
          <div id="nav-account-dropdown" class="dropdown-menu dropdown-menu-end" aria-labelledby="navbar-dropdown">
            <%= link_to "Settings", edit_patron_registration_path, class: "dropdown-item" %>
            <% if current_patron.admin? && respond_to?(:madmin_root_path) %>
            <div class="dropdown-divider"></div>
            <%= link_to "Admin Area", madmin_root_path, class: "dropdown-item" %>
            <% end %>
            <div class="dropdown-divider"></div>
            <%= button_to "Logout", destroy_patron_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>

        <% else %>
        <li class="nav-item"><%= link_to "Sign Up", new_patron_registration_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "Login", new_patron_session_path, class: "nav-link" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

sqlite_app/app/views/shared/_notices.html.erb
<% flash.each do |msg_type, message| %>
  <div class="container mt-4 mx-auto">
    <div class="alert <%= bootstrap_class_for(msg_type) %> alert-dismissible fade show" role="alert">
      <%= message %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  </div>
<% end %>